version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gitcrab-db
    environment:
      POSTGRES_USER: loco
      POSTGRES_PASSWORD: loco
      POSTGRES_DB: gitcrab_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitcrab-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://loco:loco@db:5432/gitcrab_development"
    ports:
      - "5150:5150"
    volumes:
      - ./config:/usr/app/config
      - ./assets:/usr/app/assets

volumes:
  postgres_data:

