services:
  db:
    image: postgres:15.3-alpine
    container_name: gitcrab-db
    environment:
      POSTGRES_USER: loco
      POSTGRES_PASSWORD: loco
      POSTGRES_DB: gitcrab_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loco -d gitcrab_development"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitcrab-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://loco:loco@db:5432/gitcrab_development"
    ports:
      - "5150:5150"  # Your app port
      - "22:22"    # SSH port for Git
    volumes:
      - ./config:/usr/app/config
      - ./assets:/usr/app/assets
      - git_repositories:/home/git/repositories  # Persist Git repositories
      - git_ssh_keys:/home/git/.ssh              # Persist SSH keys
    networks:
      - db
    env_file:
      - .env

      
  mail:
    image: axllent/mailpit:latest
    container_name: gitcrab-mail
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    environment:
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    networks:
      - db

volumes:
  postgres_data:
  git_repositories:  # For Git repositories persistence
  git_ssh_keys:      # For SSH keys persistence

networks:
  db:
